openapi: 3.1.1
info:
  version: 1.0.0
  title: CampusCribs
  description: CampusCribs API Implementation Specification
paths:
  /users/me:
    get:
      tags:
        - User
      summary: Get current user
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
/tags:
  get:
    tags:
      - Tag
    summary: Get all tags
    responses:
      "200":
        description: OK
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  tagCategoryId:
                    type: string

components:
  schemas:
    UserAnonymous:
      type: object
      required:
        - id
        - firstName
        - lastName
        - username
        - createdAt
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
        lastName:
          type: string
        username:
          type: string
        bio:
          type: string
        thumbnailMediaId:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
    User:
      type: object
      required:
        - id
        - firstName
        - lastName
        - username
        - createdAt
      properties:
        id:
          type: string
          format: uuid
        firstName:
          type: string
        lastName:
          type: string
        username:
          type: string
        bio:
          type: string
        thumbnailMediaId:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        email:
          type: string
          format: email
        phone:
          type: string
  parameters:
    limit:
      description: The limit of a paginated request
      in: query
      name: limit
      required: true
      schema:
        type: number
    page:
      description: The page of a paginated request
      in: query
      name: page
      required: false
      schema:
        type: number
